name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ "3.10", "2.7" ]
    container:
      image: registry.jihulab.com/gitlab-cn/mono-client/python${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Test with unittest
        run: |
          cd requests_to_curl
          python test.py
